### ISSUE TITLE
onStop doesn't work on Android

### ISSUE THREAD

**Issue by nickvo1604** [wix/react-native-interactable#104]
onStop works perfectly on iOS but doesn't work on android.
Packages version:
"react": "16.0.0-alpha.6",
 "react-native": "^0.44.0",
 "react-native-interactable": "0.0.9",

**Comment by em222iv** [comment]
+1

**Comment by cinder92** [comment]
same issue here!

**Comment by TyrealGray** [comment]
Still have this issue.
