### ISSUE TITLE
Differentiating `snapTo` from user snap in callbacks

### ISSUE THREAD

**Issue by sdeleon28** [wix/react-native-interactable#105]
Currently, `onSnap` gets fired for these two cases:

* User snaps view by manually dragging it
* Programatically snapping with `snapTo`

These two use cases are often reactions to very different types of interactions. It would be useful to have additional callbacks so that you have more granular control (e.g. `onDragSnap` vs `onProgrammaticSnap`, these names are terrible but illustrate the need).

Is this possible?

**Comment by butchmarshall** [comment]
Any workaround for this?
