### ISSUE TITLE
Apple Maps-Style Panel - suggestion

### ISSUE THREAD

**Issue by grundmanise** [wix/react-native-interactable#11]
When the card is fully visible (on the 2nd step) and the user starts panning card to the top there should be a linear deceleration (in Y position change).

**Comment by talkol** [comment]
Interesting.. let's take this as a challenge to implement.

My main goal right now is to improve the declarative API until it can cover all the basic use-cases.

This is the way to approach it with the current API: You can define another force that will kick in only when the view passes the 2nd step (by adding an `influenceArea` with specific Y values) and this force will provide the required deceleration. It could either be a friction force (see `frictionAreas`) or a spring that pulls in the other direction (see `springPoints`). Note that if you want to deceleration to take effect during drag itself, you'll need to make the drag happen using a spring with `dragWithSpring`.

It will be great if you play around with the above idea on the demo app, and see if this method succeeds in getting the result you have in mind.

If yes, I'll be happy if you share the declaration code here.

If not, then it becomes really interesting - in that case, can you think of an API improvement that will solve this?

**Comment by gastonmorixe** [comment]
@talkol I tried what you said without success, mind guiding us how would you do it? thank you

**Comment by isaachinman** [comment]
@talkol I also spent quite some time playing around with this for a particular use case.

I believe this library is fantastic for creating very simple pieces of UI, like the ones in the examples. Slideout menus, draggables, etc.

But this library is simply not equipped to be the engine behind, for example, an image cropping UI with drag-to-pan image, pinch zoom, etc.

Not sure what you meant by "basic use-cases", but currently only the most basic of basic are possible. That said, the performance is awesome.

**Comment by rotemmiz** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.

Thanks for your contribution.
