### ISSUE TITLE
Examples Not working with  CRNA 

### ISSUE THREAD

**Issue by yash2code** [wix/react-native-interactable#111]

**Comment by AaronBuxbaum** [comment]
+1. I believe that this is the same problem as #123. Still doesn't work as of 0.1.3.

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
