### ISSUE TITLE
use snapTo() :couldn't find key index in dynamic object  --> Android (fixed)

### ISSUE THREAD

**Issue by zhaiyjgithub** [wix/react-native-interactable#117]
Hi! I use Interactable in Section List. But I got this error when I call the function that this._interactableView.snapTo({x: 0, y: 0}).

> couldn't find key index in dynamic object
getInt
ReadableNativeMap.java
ReceiveCommand
InteractableViewManager.java 54
.....

My List Item code:

    `render() {
	return (
		<View style={styles.container}>
			<View style={{backgroundColor: 'red'}}>

					<View style={{position: 'absolute', right: 0, height: 75, flexDirection: 'row', alignItems: 'center'}}>
						<Animated.View style={
							[styles.button, {
								opacity: this._deltaX.interpolate({
									inputRange: [-230, -230, -180, -180],
									outputRange: [1, 1, 0, 0]
								}),
								transform: [{
									scale: this._deltaX.interpolate({
										inputRange: [-230, -230, -180, -180],
										outputRange: [1, 1, 0.8, 0.8]
									})
								}]
							}
							]} />
						<Animated.View style={
							[styles.button, {
								opacity: this._deltaX.interpolate({
									inputRange: [-165, -165, -115, -115],
									outputRange: [1, 1, 0, 0]
								}),
								transform: [{
									scale: this._deltaX.interpolate({
										inputRange: [-165, -165, -115, -115],
										outputRange: [1, 1, 0.8, 0.8]
									})
								}]
							}
							]} />
						<Animated.View style={
							[styles.button, {
								opacity: this._deltaX.interpolate({
									inputRange: [-100, -100, -50, -50],
									outputRange: [1, 1, 0, 0]
								}),
								transform: [{
									scale: this._deltaX.interpolate({
										inputRange: [-100, -100, -50, -50],
										outputRange: [1, 1, 0.8, 0.8]
									})
								}]
							}
							]} />
					</View>

					<Interactable.View
						ref = {(o) => this._interactableView = o}
						horizontalOnly={true}
						snapPoints={[{x: 0, id: 'closed'}, {x: -230, id: 'open'}]}
						onSnap={this.onDrawerSnap}
						animatedValueX={this._deltaX}>
						<View style={{left: 0, right: 0, height: 75, backgroundColor: '#e0e0e0'}} />
					</Interactable.View>

				</View>
				<TouchableOpacity onPress={() => {
					this._interactableView.snapTo({x: 0, y: 0})
				}}>
					<Text>origin</Text>
				</TouchableOpacity>
			</View>
		);
	}
	onDrawerSnap(event) {
		const snapPointId = event.nativeEvent.id;
		console.log(`drawer state is ${snapPointId}`);
	}`

Thanks a lot. Sorry, I need to learn about Android !

env:
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-interactable": "0.0.9",

**Comment by zhaiyjgithub** [comment]
I check the code and find that I call the function 'snapTo' in wrong  way.
correct:
this._interactableView.snapTo({index: 0})
the param 'index' from snapPoints in the Interactable.View.

**Comment by burhanyilmaz** [comment]
@zhaiyjgithub thanks its work 🙂
