### ISSUE TITLE
ScrollView , ListView , FlatList , Virtual List not working inside Interactable.View

### ISSUE THREAD

**Issue by imbudhiraja** [wix/react-native-interactable#119]
Here is the sample code

<View style={styles.container}>
        <Animated.View style={[styles.filterContainer, {
          transform: [{
            translateY: this._deltaY.interpolate({
              inputRange: [-130, -50],
              outputRange: [-33, 0],
              extrapolateRight: 'clamp'
            })
          }]
        }]}>
          <Animated.View style={[styles.filterTop, {
            opacity: this._deltaY.interpolate({
              inputRange: [-90, -20],
              outputRange: [0, 1],
              extrapolateLeft: 'clamp',
              extrapolateRight: 'clamp'
            })
          }]}>
            <TouchableOpacity>
              <Image style={styles.filterUp} source={{uri:"https://facebook.github.io/react/img/logo_og.png"}} />
            </TouchableOpacity>
          </Animated.View>
          <TouchableOpacity>
            <View style={styles.filterField}>
              <Text style={styles.filterFieldText}>Anywhere</Text>
            </View>
          </TouchableOpacity>
          <TouchableOpacity>
            <Animated.View style={[styles.filterField, {
              opacity: this._deltaY.interpolate({
                inputRange: [-70, -50],
                outputRange: [0, 1],
                extrapolateLeft: 'clamp',
                extrapolateRight: 'clamp'
              })
            }]}>
              <Text style={styles.filterFieldText}>Anytime</Text>
            </Animated.View>
          </TouchableOpacity>
          <TouchableOpacity>
            <Animated.View style={[styles.filterField, {
              opacity: this._deltaY.interpolate({
                inputRange: [-20, 0],
                outputRange: [0, 1],
                extrapolateLeft: 'clamp',
                extrapolateRight: 'clamp'
              })
            }]}>
              <Text style={styles.filterFieldText}>Anything</Text>
            </Animated.View>
          </TouchableOpacity>
        </Animated.View>

        <Interactable.View
          verticalOnly={true}
          snapPoints={[{y: 0}, {y: -130}]}
          boundaries={{top: -200}}
          animatedValueY={this._deltaY}>
          <ScrollView style={styles.content}>
            
          </ScrollView> 
        </Interactable.View>
      </View>

container: {
    flex: 1,
    alignItems: 'stretch',
    backgroundColor: 'white'
  },
  filterContainer: {
    backgroundColor: 'green',
    paddingTop: 10
  },
  filterTop: {
    height: 36
  },
  filterUp: {
    marginLeft: 24,
    width: 26,
    height: 26,
  },
  filterField: {
    height: 40,
    backgroundColor: 'blue',
    marginHorizontal: 10,
    marginBottom: 10,
    borderRadius: 4,
    justifyContent: 'center'
  },
  filterFieldText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 30
  },
  content: {
    padding: 20,
    backgroundColor: 'white',
    height:Constants.BaseStyle.DEVICE_HEIGHT
  },
  panelTitle: {
    fontSize: 27,
    height: 35
  },
  panelSubtitle: {
    fontSize: 14,
    color: 'gray',
    height: 30,
    marginBottom: 10
  },
  panelButton: {
    padding: 20,
    borderRadius: 10,
    backgroundColor: '#de6d77',
    alignItems: 'center',
    marginVertical: 10
  },
  panelButtonTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'white'
  },

**Comment by amirrezamahyari** [comment]
same issue

**Comment by Noitidart** [comment]
I am using RN 0.47.1 and am seeing this issue. I think there is a fix in the works here  - https://github.com/wix/react-native-interactable/issues/107#issuecomment-313058272

**Comment by Inbal-Tish** [comment]
closing in favor of issue #35
