### ISSUE TITLE
Linking error on Android and iOS

### ISSUE THREAD

**Issue by balesz** [wix/react-native-interactable#122]
This commit is messed up the react-native linking process because the native project directories are moved to the lib directory: https://github.com/wix/react-native-interactable/commit/92ce8f7258d83af60b68513cf481f95f926c68ee

If previously linked the library, then the link command has no effect and the build doesn't work.

If run the link on a new and clean react-native project, then the iOS project linked correctly but the Android project is not linked at all.

**Comment by kirakik** [comment]
Any news on this? This is quite a major issue

**Comment by silyevsk** [comment]
Fixed in 0.1.1
