### ISSUE TITLE
Notification Panel not working on Real devices!

### ISSUE THREAD

**Issue by BeginReactNative** [wix/react-native-interactable#124]
I cloned real-life-example to my computer and test it. Example working on Ios simulator , but it's not work on real device . I using samsung s8. some picture for error: 
Working with iOS Simulator: 
![simulator screen shot jul 22 2017 11 22 12 am](https://user-images.githubusercontent.com/28951651/28488255-dbad201a-6ed0-11e7-9690-4fa32d5a9fb0.png)
and not work on real device:
![error1](https://user-images.githubusercontent.com/28951651/28488262-ea2fa27a-6ed0-11e7-8238-360c58ebb6fa.png)
Please help!, thank for reading!

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to clean up and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.

Thanks for your contribution.
