### ISSUE TITLE
Windows npm install issue

### ISSUE THREAD

**Issue by jp928** [wix/react-native-interactable#129]
When I upgrade to 0.1.1, I got error from post install script on windows.
saying "ln -s " something. Obivisouly the "ln -s" command is not windows command.
Please verify it.

**Comment by jp928** [comment]
I found the problem is caused by post install script in package.json
```javascript
 "postinstall": "ln -s lib/{ios,android} ."
```

Is that possible to make this works in windows environment as well?

**Comment by BillTuan** [comment]
Same issue and Android link missing as well

**Comment by phamtienmanh** [comment]
Save isue! 'ln' is not recognized as an internal or external command

**Comment by jp928** [comment]
[same issue as ](https://github.com/wix/react-native-interactable/issues/140)

**Comment by digiwebguy** [comment]
Wow same issue still. Nobody got a fix or workaround for this one?

**Comment by fizzvr** [comment]
I'll test this issue.  So no ones update this issue about 3 months ago. We need more PR.

**Comment by iksent** [comment]
Same issue. Windows x64.

**Comment by markhu** [comment]
Issues #129 and #140 both seem to be about symlink malfunctions. Where I see it is when running under Jenkins where `./gradlew` invokes NPM/Yarn via a plugin that appears to be older than my workstation. A very frustrating example of, "It works on my computer!"
