### ISSUE TITLE
[0.1.2 Build Error]  Method does not override or implement a method from a supertype @Override

### ISSUE THREAD

**Issue by dk0r** [wix/react-native-interactable#132]
1. I incurred the following error when building `react-native-interactable@0.1.1` for android w/ `react@16.0.0.-beta3` and `react-native@0.47.1`
Note: This was not tested on iOS

**Error**:
```
~\node_modules\react-native-interactable\android\src\main\java\com\wix\interactable\Interactable.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-interactable:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

2. Issue is resolved by commenting out the `@Override` on lines-14, 19 and 24 of `...\node_modules\react-native-interactable\android\src\main\java\com\wix\interactable\Interactable.java` ([here](http://i.imgur.com/blSV6wT.png))

**Comment by nonameolsson** [comment]
What's the status on this? Merge possible?

**Comment by yash2code** [comment]
not solved

**Comment by nonameolsson** [comment]
@yash2code https://github.com/CongenialData/react-native-interactable/pull/1/files.

**Comment by dk0r** [comment]
This issue is still present in `react-native-interactable@0.1.2`

**Comment by dk0r** [comment]
This same issue persists for the included `real-life-example` in `react-native-interactable@0.1.2`. 
The `@Override` which must be commented out is located in the following directory:

....\real-life-example\node_modules\react-native-interactable\\**_lib_**\\android\src\main\java\com\wix\interactable

**Comment by Inbal-Tish** [comment]
#131
