### ISSUE TITLE
[0.1.1 Bug] onPress callbacks not reliably triggered from inside <Interactable.View>

### ISSUE THREAD

**Issue by dk0r** [wix/react-native-interactable#134]
**Issue**: `onPress` callbacks are not consistently triggered when nested inside an `<Interactable.View>`. As shown in the example below, the `<TouchableOpacity>` has to be rapidly pressed between 10-50 times in order to have a chance of the `onPress` being triggered. Removing the `<Interactable.View>` resolves this issue and restores the reliable responsiveness of the `onPress` callback.

**Note**: This issue only occurs on a physical device (e.g. a Google Pixel XL). This behavior is **not** exhibited on an emulated Pixel XL (e.g. http://i.imgur.com/ZEbHu4m.png). Setting the `animatedNativeDriver` prop and disabling `JS Dev Mode` in android Dev settings (shown [here](http://i.imgur.com/sWuer8Z.png)) has no effect.

**Versions used**: react-native-interactable@0.0.9-0.1.1, react-native@0.47.1, react@16.0.0-beta3
```
   {DATA.filter.map( item =>
            <Interactable.View
              //animatedNativeDriver={true} // setting animatedNativeDriver to true did not help
              initialPosition={{ x: 0, y: 0 }}
              snapPoints={[{ x: 0, y: 0 }]}
              key={item.id}
            >
              <TouchableOpacity
                onPress={() => console.log('I was pressed!!!!!')}
              >
              </TouchableOpacity>
            </Interactable.View> 
    )}
```

**Comment by Inbal-Tish** [comment]
Closing this issue in favor of issue #187
