### ISSUE TITLE
Doesn't support borderRadius

### ISSUE THREAD

**Issue by zhantx** [wix/react-native-interactable#138]
Hey, I am working on the apple map style panel recently, I used the codes from real life example and it works fine on iOS. But when it comes to Android, I will need to use `elevation` to have the shadow effect and it requires `backgroundColor`. In this case, I also need to set `borderRadius` (topLeft and topRight) but seems the interactable view doesn't support this style.

**Comment by adon94** [comment]
Having the same issue also. Did you find a solution?

**Comment by EricPKerr** [comment]
@zhantx Does making the interactable view transparent (as just a container) and having the child view have the styling work?

**Comment by adon94** [comment]
@EricPKerr that's what I ended up doing with a small margin on the child view. Works fine for me.

**Comment by EricPKerr** [comment]
Great - this should be closed then.
