### ISSUE TITLE
react-native-interactable is not installing

### ISSUE THREAD

**Issue by kn1810** [wix/react-native-interactable#140]
while am installing npm install --save react-native-interactable, i am getting error

> react-native-interactable@0.1.1 postinstall projectdirectory\node_modules\react-native-interactable
> ln -s lib/{ios,android} .

'ln' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jamesdyer8** [comment]
I had this same issue trying to install via CMD or Powershell. However, installation was successful when I ran the same command using gitBash CLI. Hope that's helpful.

**Comment by MasterDaveh** [comment]
Thanks @jamesdyer8, that worked for me too!

**Comment by AugustoAleGon** [comment]
@jamesdyer8 Excellent solution.

**Comment by LannyCodes** [comment]
@jamesdyer8 This solutes my issue,Thanks!

**Comment by ButtersHub** [comment]
Fixed in ver 0.2.0

**Comment by dreamHeroK** [comment]
@jamesdyer8  thanks.

**Comment by kuldeepoza** [comment]
remove folder from node_module 
react-native-interactable

**Comment by phungvanthi** [comment]
@jamesdyer8 thanks.
