### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by Quadriphobs1** [wix/react-native-interactable#144]
Cannot install the plugin on windows app, get an error each time i tried, 'ln -s' not recognised as an internal or external command, any help please

**Comment by ceasterday** [comment]
I have the same issue, ln is a linux command not available on windows. I have access to a macbook that I can use for now but I'm evaluating this library for a new project and some of the developers may only have windows machines. It would be nice if it could be installed on all platforms.

**Comment by Quadriphobs1** [comment]
I think i am able to install it on my window machine now, i used Git Bash console, but at first try it doesnt work but on the second try it worked.

**Comment by ceasterday** [comment]
Adding through git bash worked for me as well, thanks.

**Comment by alonbardavid** [comment]
Why is ln necessary?

Usually in react-native packages, the ios/android folder is in the root folder. Alternatively you can request users of the library to link manually to src/ios or src/android.

**Comment by alonbardavid** [comment]
Symlinks play havoc with a lot of systems (Yarn and npm for one) and should be done manually via a script in very rare cases.

**Comment by ButtersHub** [comment]
Fixed in ver 0.2.0

**Comment by bbeckk** [comment]
It is still not working in windows

**Comment by oscarnevarezleal** [comment]
It is still not working in windows
