### ISSUE TITLE
"package com.wix.interactable" does not exist after linking

### ISSUE THREAD

**Issue by hoboman313** [wix/react-native-interactable#149]
Not doing anything special. After I `react-native link react-native-interactable` I get a "package com.wix.interactable does not exist" when building my app on Android. My env is windows 10, RN ^0.47. `ln -s` does work in my environment so it is not an issue as some of the other tickets.

I do see the com.wix.interactable package show up when I open my app in Android Studio, but all references to the package classes fail with "Cannot resolve". Kind of confused with what's going on here.

**Comment by hoboman313** [comment]
Took me a while to figure out in android studio to add the "react-native-interactable" module as a dependency. This added "compile project(':react-native-interactable')" to my build.graddle. 
I'm curious as to why this wasn't done by the linking command.

**Comment by essuraj** [comment]
linking command not adding ``` implementation project(':react-native-interactable')```
