### ISSUE TITLE
console.error: "invariant@..." (android, react native 0.44.2)

### ISSUE THREAD

**Issue by MeisterTea** [wix/react-native-interactable#151]
Hi, here is my configuration :

react-native 0.44.2
react 16.0.0-alpha-6
platform android

I can't use the library without debugger. If I do so, I have an error as soon as I reach the screen containing an interactable component.
Please note that the library runs fine with the debugger connected.

The error is this one : 

console.error: "invariant@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1719:24

It refers to this block : 

function invariant(condition, format, a, b, c, d, e, f) {
--
  | validateFormat(format);
  |  
  | if (!condition) {
  | var error;
  | if (format === undefined) {
  | error = new Error('Minified exception occurred; use the non-minified dev environment ' + 'for the full error message and additional helpful warnings.');
  | } else {
  | var args = [a, b, c, d, e, f];
  | var argIndex = 0;
  | error = new Error(format.replace(/%s/g, function () {
  | return args[argIndex++];
  | }));
  | error.name = 'Invariant Violation';
  | }
  |  
  | error.framesToPop = 1;
  | throw error;
  | }
  | }

Any idea ?

**Comment by CorentinHeroux** [comment]
I am experiencing the same issue, can anyone help please ?

**Comment by MeisterTea** [comment]
Here is the following trace which sometimes appeared 
    invariant(renderedElement === null || renderedElement === false || React.isValidElement(renderedElement), '%s.render(): A valid React element (or null) must be returned. You may have ' + 'returned undefined, an array or some other invalid object.', this.getName() || 'ReactCompositeComponent');
