### ISSUE TITLE
dynamically changing boundaries

### ISSUE THREAD

**Issue by renrizzolo** [wix/react-native-interactable#155]
Hi,
I'm making an image gallery, and I'm using onLayout to get the new Dimensions when the device rotates, then I create new snapPoints and boundaries based on the new dimensions.

The problem I'm having is the new boundary doesn't seem to be respected. The snapPoints update fine, but it gets stuck at what seems to be the original boundary that was set on mount.

When the dimensions are changed a function like this runs:

```
	createGallery(data, Dimensions) {
		const snapPoints = {
			points: [],
			leftBoundary: (-(Dimensions.width) * (data.length - 1) + -(Dimensions.width / 3)),
			rightBoundary: Dimensions.width / 3,
		 };

		data.map((item, i) => {
			array = { x: -(Dimensions.width) * i, y: 0, id: `'${i}'`, tension: 100, damping: 0.8 };
			snapPoints.points.push(array);
		});

		this.setState({ snapPoints });
	}
```

Then it is rendered like this:
```
const { snapPoints } = this.state;
...
<Interactable.View
	ref="galleryInstance"
	horizontalOnly
	dragEnabled
	dragToss={0.5}
	animatedValueX={this._GalleryDeltaX}
	animatedNativeDriver
	boundaries={
		{ 
			right: snapPoints.rightBoundary, 
			left: snapPoints.leftBoundary, 
			bounce: 0.25, 
			haptics: true 
		}
	}
	snapPoints={snapPoints.points}
	initialPosition={{ x: 0, y: 0 }}
>
```

Not sure if it's a bug or if I'm doing something wrong...

----
RN 0.48.1
Interactable 0.1.3

**Comment by Mbompr** [comment]
I have the same issue on android with RN 0.41.0 and Interactable 0.1.3. Did you find any workaround?

**Comment by iksent** [comment]
Anybody found any workaround?

**Comment by Mbompr** [comment]
My pull request #162 works, I'm using it in production.

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to clean up and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.
Thanks for your contribution.
