### ISSUE TITLE
It seems Interactable.View will cache the children node

### ISSUE THREAD

**Issue by TyrealGray** [wix/react-native-interactable#156]
![bug](https://user-images.githubusercontent.com/5646693/30594969-18545544-9d50-11e7-8a26-a8ed047bb023.gif)

code:

	render() {
		return (
			<View style={Styles.cSwipeOut_background}>

				<View style={Styles.cSwipeOut_buttonGroup}>
					{this.props.buttonGroupView}
				</View>

				<Interactable.View
					ref={( ref ) => {
						this.swipe = ref;
					}}
					horizontalOnly={true}
					boundaries={{ left: -100, right: 0 }}
					snapPoints={[
						{ x: 0 },
						{ x: -155 },
					]}
				>
					<View style={Styles.cSwipeOut_center}>
						{this.props.children}
					</View>
				</Interactable.View>

			</View>
		);
	}

And I warp it up inside of a SectionList component

**Comment by MrPluto** [comment]
#60 
#29

**Comment by burhanyilmaz** [comment]
@TyrealGray how do this? Can you help me?
how close auto?
