### ISSUE TITLE
onDrag callback installed crashes apps in iOS since #161

### ISSUE THREAD

**Issue by joaoanes** [wix/react-native-interactable#165]
Hey guys, love your work!

Since #161, onDrag callbacks are broken if there are no snapPoints defined for that `Interactable.View` on iOS. 
I'm not an iOS developer by trade, but it seems `reportDragEvent:targetSnapPointId:` accepts nil values for `targetSnapPointId`, which results in a `NSInvalidArgumentException` since we just tried to put those nil values in an `NSDictionary`. 
This happens because `findClosestPoint:toPoint:withOrigin:`, when snapPoints is nil, returns a nil point instead of something with an id of `@""`, and that null `point.id` is passed on straight to `reportDragEvent:targetSnapPointId:`, instead of an empty string instead. Should be fairly reproducible.

I could contribute a fix but I'm unaware of you how might want to fix this - we could make sure there's a good default value when there are no snap points, or we could simply replace nil values with empty strings on `reportDragEvent:targetSnapPointId:`.

https://gist.github.com/joaoanes/032a2463aba5ad570309cb3ff05ac295
Stack trace after moving an `Interactable.View` with a simple `onDrag` prop .

Code for the above:
https://gist.github.com/joaoanes/c6c195770b0f142c7ffbdb98b53cf5d0
package.json:
https://gist.github.com/joaoanes/eb54a3813dbab6148455940cca4b2989

**Comment by nixterrimus** [comment]
I'm seeing this too!

**Comment by MiLeung** [comment]
Same. Too bad this project is not being maintained (Wix is looking for maintainers)
