### ISSUE TITLE
Deployment target set to 10.2 causes warnings in example project and real project(s)

### ISSUE THREAD

**Issue by mattijsf** [wix/react-native-interactable#166]
In our projects we use iOS 9.0 as our deployment target. But the Interactable library uses 10.2 as deployment target. I also notices that the example project even uses a deployment target of 8.0.

During build time this causes the following warnings (15):
```
ld: warning: object file (~/Library/Developer/Xcode/DerivedData/.../Debug-iphonesimulator/libInteractable.a(InteractableView.o)) was built for newer iOS version (10.2) than being linked (9.0)
ld: warning: object file (~/Library/Developer/Xcode/DerivedData/.../Debug-iphonesimulator/libInteractable.a(PhysicsBounceBehavior.o)) was built for newer iOS version (10.2) than being linked (9.0)
... 13 more
```

Is there a technical reason why the deployment target is set like this? If I change it to 9.0 it seems to work fine. But I prefer not to do this every time I fetch my dependencies and this setting gets overridden.

In real life I think developer still want to support 9.0 / 10.0 / 10.2 as a deployment target. I don't know the numbers but I think it is too soon to unsupport it.

Should I open a PR?

**Comment by Inbal-Tish** [comment]
https://github.com/facebook/react-native/issues/19346
