### ISSUE TITLE
Change state programmatically without an interaction

### ISSUE THREAD

**Issue by jmstout** [wix/react-native-interactable#17]
You all have done some really brilliant work here – kudos! 

One thing I'm wondering – would it be feasible to add a method for changing the Interactable state programmatically? Something like `snapTo({x: 360})`?

This would help in the case of using an `Interactable.View` as an app menu drawer. It is sometimes necessary to provide a "menu button" that toggles an open or closed state `onPress`, as an alternative to a swipe interaction.

I've been unable to discern a way of doing this, given the current API. My understanding is that `animatedValueX` and `animatedValueY` are essentially read-only?

Thanks!

**Comment by frantic** [comment]
I think you can still change the animated values using `Animated` APIs, however the `<Interactable.View />` only writes to it, so changes won't affect the view itself.

Indeed, would be really cool to have more programmatic control over the `<Interactable.View />` views.

**Comment by jp928** [comment]
@jmstout 
Thanks for your reply. But I don't really get your point. What I am suppose to do was something like:

<Interactable.View initialPosition={{x: 0, y: -screenHeight}} animatedValueY={{this.state.deltaY}}>
   {modalContentGoesHere}
</Iteractable.View>

I expected I could move the component above on the axisY by using Animated.timing(this.state.deltaY).start();

Is there anyway to achieve this in a similar way by using current APIs?

**Comment by talkol** [comment]
@jp928 the `animatedValueY` prop is write-only, meaning the library will write the interactable view's position to it.

There is no way to change the interactable view position through the animated value.

I think the correct API would be something imperative like `snapTo({x,y})` which will work using a `ref`. I don't see a declarative way to achieve this.

**Comment by talkol** [comment]
I'm closing this with duplicate at #18

**Comment by talkol** [comment]
I just added `snapTo` imperative command as well due to issue #44
