### ISSUE TITLE
Manifest merge fails after install

### ISSUE THREAD

**Issue by Noitidart** [wix/react-native-interactable#171]
> Manifest merger failed : Attribute application@theme value=(@style/SplashTheme) from AndroidManifest.xml:18:7-41 is also present at [enter_the_gunbook:react-native-interactable:unspecified] AndroidManifest.xml:15:9-40 value=(@style/AppTheme).
      Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:13:5-30:19 to override.

The **workaround** for this is to modify AndroidManifest.xml with this:

```
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
     package="com.trustedfamily"
     android:versionCode="1"
-    android:versionName="1.0">
+    android:versionName="1.0"
+    xmlns:tools="http://schemas.android.com/tools">
 
     <uses-permission android:name="android.permission.INTERNET" />
     <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
@@ -13,6 +14,7 @@
 
     <application
       android:name=".MainApplication"
+      tools:replace="theme"
```

It would be nice if a fix can happen.

I have been having this problem since RN v0.48

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
