### ISSUE TITLE
Is it possible to choose drag direction, e.x, left or right?

### ISSUE THREAD

**Issue by hellomaya** [wix/react-native-interactable#173]
Hi,

Thanks for this awesome component, working great in iOS device.

I have a question, in the real-life-example, it had RowAction example, showed how to make a swipeable row, very helpful, so I am wondering is it possible to disable one side drag direction, for example, left or right? I know there is a dragEnabled property, if there is another dragDirection property would be great:

dragDirection = left | right | both <default>

Thank you!

**Comment by karltaylor** [comment]
Boundaries might be what you're after

**Comment by hellomaya** [comment]
@karltaylor thank you, perfect!!
