### ISSUE TITLE
Left swiped component is visible in StackNavigators previous View

### ISSUE THREAD

**Issue by mafiusu** [wix/react-native-interactable#174]
Hello the component which I swipe to the left to dismiss is visible in the Stack Navigators previous view for 1 sec and then hides out. Can anyone tell me how I can avoid this?

```
<Interactable.View
               horizontalOnly={true}
               snapPoints={[
               {x: 0, damping: 0.5},
               {x: -360}]}
               onSnap={null}>

... </Interactable.View>
```

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to clean up and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.
Thanks for your contribution.
