### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by TheDutchCoder** [wix/react-native-interactable#185]
When importing this library I get an Invariant Violation:

```js
import Interactable from 'react-native-interactable'

class ListItem extends React.component {
  render() {
    return (
      <Interactable.View horizontalOnly={true}>
        <View>
          <Text>Drag me!</Text>
        </View>
      </Interactable.View>
    )
  }
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/1668207/36102627-dfc409c4-0fda-11e8-8781-83833b8979dc.png)

**Comment by mafiusu** [comment]
I'm having the same issue after upgrading to the latest React Native version.

**Comment by lfalcao** [comment]
It's working here...

- react 16.2.0
- react-native 0.52.2
- react-native-interactable 0.1.10

`import React from 'react'
import {
  View,
  Text
} from 'react-native'
import Interactable from 'react-native-interactable'

export class Item extends React.Component {
  render() {
    return (
      <Interactable.View horizontalOnly={true}>
        <View>
          <Text>Drag me!</Text>
        </View>
      </Interactable.View>
    )
  }
}`

**Comment by TheDutchCoder** [comment]
That's an older version of react native. We're using 0.53.0

**Comment by lfalcao** [comment]
I can reproduce this only when I unlink the native library. So try to unlink and link to see if it works...

Tested again and working with: 
- react-native@0.53.0
- react-native@0.54.0-rc.3

**Comment by ivanesi** [comment]
the same
react-native: 0.53.2

**Comment by joaom182** [comment]
+1

**Comment by phillip055** [comment]
Any update?

**Comment by mhayta** [comment]
+1

**Comment by dekemega** [comment]
+1

**Comment by seanyusa** [comment]
I had this issue just now and found out that it was erroring because I forgot running `pod install` in the `ios` directory

**Comment by Inbal-Tish** [comment]
Please make sure to link native properly. In any case I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.

**Comment by tunm1228** [comment]
Please check Libraries Xcode
