### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by Zedonboy** [wix/react-native-interactable#188]
`error C:\Dev force\Mobile Development Hub\Cubix\node_modules\react-native-interactable: Command failed.
Exit code: 1
Command: ln -sf lib/{ios,android} .
Arguments:
Directory: C:\Dev force\Mobile Development Hub\Cubix\node_modules\react-native-interactable`

i get this error every time, you have any idea whats wrong.

node 8.4.0
react-native 0.51
react 16.0

**Comment by kezax94** [comment]
on Windows the equivalent of ln -sf is mklink /D
this is a postinstall script in package.json

**Comment by Zedonboy** [comment]
This issue solved it #140
