### ISSUE TITLE
Error builiding (PhysicsBehavior.m)

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-interactable#19]
I'm getting the following:

```
PhysicsBehavior.m
Unknown type name 'UIImpactFeedbackGenerator'
impliciit conversion of an Object-C pointer to 'int*' is disallowed with ARC
Use of undeclared identifier 'UIImpactFeedbackStyleLight'
Bad receiver type 'int*'
```

**Comment by talkol** [comment]
[`UIImpactFeedbackGenerator`](https://developer.apple.com/reference/uikit/uiimpactfeedbackgenerator) is an API that exists in iOS SDK 10+

You don't need a phone with iOS 10 to run it (the code checks if this API is available in runtime IMO), but you do need to build on an Xcode that supports iOS 10 SDK.

My guess is that your Xcode needs updating. I'm building with Xcode 8.2.1.

Under `Project -> Build Settings -> Architectures -> Base SDK` you should see `Latest iOS (iOS 10.2)`

If updating resolves your issue, please close

**Comment by smooJitter** [comment]
Thanks @talkol.  Im running Xcode 8.3 beta 4 and Latest iOS ( iOS 10.3 )

**Comment by smooJitter** [comment]
Does this mean I need need to run Xcode 8.2?

**Comment by LeoNatan** [comment]
What SDK are you compiling against?
`UIImpactFeedbackGenerator` is a symbol found in iOS 10 SDK. You may be using Xcode 8, but compiling against an old SDK.

**Comment by smooJitter** [comment]
@LeoNatan how would I know?

**Comment by LeoNatan** [comment]
Check the Base SDK for your project. I just compiled the example project on the latest Xcode 8.3 beta, and it compiles without issues.

**Comment by talkol** [comment]
`Project -> Build Settings -> Architectures -> Base SDK`

Another question - @smooJitter, which project exactly are you trying to build?

**Comment by LeoNatan** [comment]
Check both project and target build settings.

**Comment by smooJitter** [comment]
@talkol I hadn't gotten around to coding anything.  I installed the package into a fresh react-native project.

**Comment by smooJitter** [comment]
Update:  
I started from scratch. 

1. react-native init...  
2 yarn react-native-interactable.

The vanilla  welcome appears.  Nevertheless I have 19 warnings.

**1 React warning**
`/Users/smoojitter/Documents/DEV/clients/JitterNavigator/node_modules/react-native/React/Modules/RCTUIManager.m:239:28: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead`

**3 Interactable warnings**
```
Semantic Issue Group
/Users/smoojitter/Documents/DEV/clients/JitterNavigator/node_modules/react-native-interactable/ios/Interactable/InteractableView.m:309:16: Incompatible pointer types returning 'UIView *' from a function with result type 'RCTRootView *'

/Users/smoojitter/Documents/DEV/clients/JitterNavigator/node_modules/react-native-interactable/ios/Interactable/PhysicsBehavior.m:21:17: Method definition for 'executeFrameWithDeltaTime:onObject:' not found

/Users/smoojitter/Documents/DEV/clients/JitterNavigator/node_modules/react-native-interactable/ios/Interactable/PhysicsBehavior.m:64:112: Implicit conversion from enumeration type 'enum UIImpactFeedbackStyle' to different enumeration type 'UITableViewStyle' (aka 'enum UITableViewStyle')
```
15 warnings like this

`ld: warning: object file (/Users/smoojitter/Library/Developer/Xcode/DerivedData/JitterNavigator-dffibsenogsrayceobumsxbhbefb/Build/Products/Debug-iphonesimulator/libInteractable.a(InteractableView.o)) was built for newer iOS version (10.2) than being linked (9.1)`

You maybe aware, Xcode 8 does not appear to support iOS 10, I'm not sure how concerned I should be but 19 warnings with only one package installed is a little bit worrisome.  lol  If I get this get this to work with react-native-navigation@next... then I'm good to go.  

Thanks for your help.

**Comment by talkol** [comment]
Did you manage to resolve this?

**Comment by talkol** [comment]
Please reopen if this is still an issue
