### ISSUE TITLE
Cannot read property 'View' of undefined 

### ISSUE THREAD

**Issue by ChenCodes** [wix/react-native-interactable#191]
Hi all!

I was trying to get the Google maps sliding card to work but I'm getting this compiling error:
<img width="415" alt="screen shot 2018-03-13 at 1 41 22 pm" src="https://user-images.githubusercontent.com/7213887/37368793-7abde2b0-26c4-11e8-8df6-930f352348dd.png">

Here's the code that I copy pasted in:
<img width="829" alt="screen shot 2018-03-13 at 1 41 12 pm" src="https://user-images.githubusercontent.com/7213887/37368756-5e5027e6-26c4-11e8-95ca-734030f2c0ad.png">

Any help would be appreciated!

**Comment by ChenCodes** [comment]
I'm guessing it has to do with Interactable.View element, when I comment that out then it doesn't break

**Comment by BonnieMilian** [comment]
I'm getting crashes too on the release version. I'm using RN 0.50.0, which one are you using?

react-native-interactable Which RN version supports?

**Comment by mkuczera** [comment]
Did you correctly linked the react-native-interactable library? Seems like he don´t get the NativeModules Reference

**Comment by BonnieMilian** [comment]
I found that was a View.PropType problem, because is deprecated on React 16, the library must be updated.
Mean while I manually change it to ViewPropTypes from 'react-native'

**Comment by rotemmiz** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.

Thanks for your contribution.
