### ISSUE TITLE
Component 'InteractableView' re-registered bubbling event 'topDrag'

### ISSUE THREAD

**Issue by mattermoran** [wix/react-native-interactable#195]
Getting this error. React Native v0.53.3

![img_d5199a879641-1](https://user-images.githubusercontent.com/29712386/37818543-7325d5e6-2eb5-11e8-8f51-5dd1e75b9f81.jpeg)

**Comment by mkuczera** [comment]
Can you provide more Informations? Implementation and Usage in your Project?

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to clean up and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.
Thanks for your contribution.
