### ISSUE TITLE
Crash when providing `onSnap` without `id`

### ISSUE THREAD

**Issue by frantic** [wix/react-native-interactable#20]
[The documentation](https://github.com/wix/react-native-interactable/blob/master/PROPS.md) says `id` is optional for `snapPoints`, however [this code](https://github.com/wix/react-native-interactable/blob/master/ios/Interactable/InteractableView.m#L202) will crash if `id` is `nil` ("attempt to insert nil object from objects[1]").

Should be pretty easy to fix with `RCTNullIfNil`.

**Comment by talkol** [comment]
I couldn't reproduce this on master

I deleted the `id` field from this example:
https://github.com/wix/react-native-interactable/blob/master/example/src/IconDrawer.js#L62

But there were no crashes

**Comment by MrCeleryman** [comment]
Was this not fixed by #8 ?

**Comment by frantic** [comment]
Sorry, my bad! Was using the npm-published version of this package (`0.0.4` at the time), seems like #8 fixed the issue. Thanks!
