### ISSUE TITLE
Unable to access a specific children item in FlatList

### ISSUE THREAD

**Issue by unmec** [wix/react-native-interactable#202]
I am not sure that this is a specific issue for this repo. But a hint would be much appreciated.

Basically what I am doing is this:
```
constructor(props) {
  this._edit;
  this.state = {
    data: [{"name": "David", "color": "blue"}, {"name": "Celine", "color": "red"}, {"name": "John", "color": "black"}]
  }
}

render() {
  return(
    <FlatList
      data = {this.state.data}
      keyExtractor={(item, index) => index}
      renderItem={({item}) => (
        <Interactable.View
          ref={(index) => this._edit = index }
          snapPoints = {[{x:0}, {x: -100}]}
        >

          <TouchableHighlight onPress={() => this._edit.changePosition({x:0})}>
            <Text>Edit</Text>
          </TouchableHighlight>

        </Interactable.View>
      )}
    </FlatList>
  )
}
````

When click on Edit, it's always the last child that get called. Am I missing something?
Many thanks in advance.

**Comment by unmec** [comment]
Looks like an id entry for data is a must.
Using index the refs get overwritten hence only the last one is preserved.

**Comment by hungdev** [comment]
@unmec could you tell me how to call ref?

**Comment by hungdev** [comment]
i resolve by using the way  here: https://stackoverflow.com/questions/46261049/create-a-unique-ref-for-each-element-while-renderitem-in-a-sectionlist-flatli

**Comment by jordangrant** [comment]
@hungdev thanks man
