### ISSUE TITLE
NullPointerException if snapPoints is not provided [Android]

### ISSUE THREAD

**Issue by isaachinman** [wix/react-native-interactable#203]
Hi there. I'm attempting to build some interactive UI with this library that does not require any "snapping" behaviour. I set up a basic start on iOS, which worked great:

    <Interactable.View
      frictionAreas={[{ damping: 0.9 }]}
      boundaries={{
        bounce: 0.2,
        top: this.topBoundary,
        bottom: this.bottomBoundary,
        left: this.leftBoundary,
        right: this.rightBoundary,
      }}
    >
      <Image
        source={{ uri: this.props.uri }}
        style={this.imageStyles}
      />
    </Interactable.View>

Then I booted this on an Android (8.0.0) device, and immediately saw a crash on the `handleEndOfDrag` event:

    java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.wix.interactable.InteractablePoint.id' on a null object reference
        at com.wix.interactable.InteractableView.handleEndOfDrag(InteractableView.java:313)
        at com.wix.interactable.InteractableView.handleTouch(InteractableView.java:261)
        at com.wix.interactable.InteractableView.onTouchEvent(InteractableView.java:232)

After a lot of playing around, I've found that if I add `snapPoints`, this crash does not occur. I specifically do not want `snapPoints`, though.

Maybe someone who is familiar with the codebase can understand what's going on quite simply?

**Update:** Yeah, looks like there is a direct reference to `snapPoints` here:

https://github.com/wix/react-native-interactable/blob/master/lib/android/src/main/java/com/wix/interactable/InteractableView.java#L312

**Temporary fix:**

    snapPoints={[{ x: 0, tension: 0 }]}

**Comment by mkuczera** [comment]
Hi,
thank you for your feedback. A PR for this issue is already opened and should be merged soon:
https://github.com/wix/react-native-interactable/pull/196/files#diff-98bccd77c92c98327f12ba3fa7b8115c

**Comment by isaachinman** [comment]
Ah, great to hear. I'll close this issue, then.
