### ISSUE TITLE
Native component for InteractableView does not exist

### ISSUE THREAD

**Issue by sewerrat** [wix/react-native-interactable#204]
Hi! 
I've tried this module. I followed Installation instruction:

- Install the package from npm

> npm install react-native-interactable --save

- Link the native library to your project

> react-native link react-native-interactable

However, I see only one line show:
> rnpm-install info iOS module react-native-interactable is already linked 

Mean android haven't linked yet?

Actually I tried running in Android devices, the following error show: 
> Native component for "InteractableView" does not exist

I also add this line to package.json - dependencies:
> "react-native-interactable": "https://github.com/wix/react-native-interactable.git#d8c8f08f2b805070eac333124149ce87132a986e",

Still same error..

Can you show me how to link Android module?
Thanks!

**Comment by sewerrat** [comment]
I tried but still same. I will try linking manually. 
Thanks for your support!

**Comment by sewerrat** [comment]
I also tried with above edited configurations. It worked I think, pass that phase, but other error: 
> /home/rat/work-space/Mallin-app/node_modules/react-native-interactable/lib/android/src/main/java/com/wix/interactable/Interactable.java:19: error: method does not override or implement a method from a supertype
 >   @Override

Please help me handle it.
Thanks!

**Comment by sewerrat** [comment]
I think I found problem. 
Your function `createJSModules` has been deprecated: oblador/react-native-vector-icons#515. You should remove it.
I tried commenting this function, now can build. Praying for me to get no other issues hehe.

**Comment by eraldojr** [comment]
Hi Guys,
In my case I was debugging my app over WiFi with packager running with `react-native start
` and I simply connect the phone into USB cable and re-run`react-native run-android
` and worked.

**Comment by rotemmiz** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.

Thanks for your contribution.
