### ISSUE TITLE
example missing

### ISSUE THREAD

**Issue by elanpang** [wix/react-native-interactable#208]
I can't find the example folder and the link point to 404.

**Comment by mkuczera** [comment]
Everything is moved to a global playground project. Will update the Readme

**Comment by oleole90** [comment]
@mkuczera can you plz give a short guide on how to access / run the examples? Thanks.

**Comment by mucyomiller** [comment]
@oleole90  go in root directory of cloned project then run
`react-native run-ios  --project-path  playground/ios/`

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
