### ISSUE TITLE
Enable onPress for interaction

### ISSUE THREAD

**Issue by ankitbisht143** [wix/react-native-interactable#215]
Can I put onPress function for interactable.
Means instead of dragging views, I want to put a onPress function. Whenever user clicks on the interactable view. It should drag.

Thanks for this wonderful library.

**Comment by kevinNejad** [comment]
First you need to set a reference to your Interactable.View
`<Interactable.View
                    horizontalOnly
                    dragEnabled={false}
                    snapPoints={[
                        { x: 360 },
                        { x: 0, damping: 0.5 },
                        { x: -360 }]}
                    ref = {ref => this.animationRef = ref}
                >`
Then use available Intractable methods , e.g.
`<TouchableOpacity 
              onPress={() => this.animationRef.changePosition({x: 120, y: 40})}
            >`

**Comment by Inbal-Tish** [comment]
Thank you @kevinNejad
