### ISSUE TITLE
Running it as 'xcode' works fine. Will it fail if run as 'react-native run-ios'?

### ISSUE THREAD

**Issue by godesani** [wix/react-native-interactable#216]
hi guys.
The current problem is that xcode runs fine,
If you run 'react-native run-ios' on the cli screen
The error screen "interactableView does not exist."
We also did a 'react-native link' and manually linked to android and xcode.
I do not have a sense of what's wrong.
Help!

**Comment by godesani** [comment]
In the project directory, the build folder for each OS was a problem ... After the deletion, it works well.

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
