### ISSUE TITLE
can't compile.  gradle can't find junit:junit and com.facebook.react:react-native:+

### ISSUE THREAD

**Issue by fukai007** [wix/react-native-interactable#217]
Failed to resolve: junit:junit:4.12
Show in File
Show in Project Structure dialog

Failed to resolve: com.facebook.react:react-native:+
Show in File
Show in Project Structure dialog

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
