### ISSUE TITLE
Nesting Interactable.Views

### ISSUE THREAD

**Issue by FakeYou** [wix/react-native-interactable#22]
Is it possible to nest Interactable.Views? I want to create something like the notification panel like example but with the functionality to swipe away the individual notifications like the Google-Now card.

I tried too make it myself quickly but couldn't get it to work. The parent view seems to always handle the panning.

My structure looks something like this:

```
<Interactable.View verticalOnly>         // notification panel
  <Interactable.View horizontalOnly />   // nofitication
  <Interactable.View horizontalOnly />   // nofitication
  <Interactable.View horizontalOnly />   // nofitication
  <Interactable.View horizontalOnly />   // nofitication
</Interactable.View>
```

Anyway, thanks for the amazing library!

**Comment by talkol** [comment]
hmm... good one. Nesting them is going to be annoying with the touches. But vertical within horizontal should theoretically resolve the touch collisions.. I'll test it out

**Comment by chrise86** [comment]
Did anyone ( @talkol, @FakeYou ) manage to achieve this?

**Comment by rotemmiz** [comment]
Closing this issue in favour of #241, it has a working demonstrating issues with nested view on Android
