### ISSUE TITLE
Interactable View keep position on simblings when removed

### ISSUE THREAD

**Issue by joaom182** [wix/react-native-interactable#221]
![jul-07-2018 03-57-24](https://user-images.githubusercontent.com/3612098/42407898-2029f8f8-819a-11e8-88d9-5b6babda2684.gif)

**Comment by glothos** [comment]
Did someone manage to make it work? Even with the unique key prop inside a map function this problem persists.

**Comment by joaom182** [comment]
I did a work around, reseting the position of card on action execution. But the original issue persist.

**Comment by glothos** [comment]
Yea, it won't reset the position automatically due to React recycling the View on re render.

**Comment by joaom182** [comment]
@glothos i agree with you, but the expected natural behavior is for not reset the specific node element, not the node position.
