### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by IanCStewart** [wix/react-native-interactable#224]
After merging #198 the real-life-example got moved but the readme has stayed the same. This makes it really hard to figure out how to run those in the current master branch.

**Comment by alexfqc** [comment]
@IanCStewart  do you know how?

**Comment by Inbal-Tish** [comment]
I am closing the Issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
