### ISSUE TITLE
dragToss and dragWithSpring props doesn't work on Android

### ISSUE THREAD

**Issue by alpfilho** [wix/react-native-interactable#226]
**Environment:**
Android 7.1.2

**Packages:**
react: 16.3.1 
react-native: 0.55.4
react-native-interactable: 0.1.10

**Values (Weird values just for example and visualization bellow of the diferences between behaviors)**
```
dragWithSpring={{ tension: 2000, damping: 0 }}
dragToss={0}
```
**Behaviors**
iOS:
![kapture 2018-08-21 at 10 25 18](https://user-images.githubusercontent.com/17249907/44404166-b0505980-a52c-11e8-908d-b271785c71e2.gif)

Android:
![kapture 2018-08-21 at 10 28 59](https://user-images.githubusercontent.com/17249907/44404422-353b7300-a52d-11e8-9154-2ad825ba0c7e.gif)

I only want that both platforms to have the same behavior

**Comment by Inbal-Tish** [comment]
resolved with PR #255
