### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by mnlbox** [wix/react-native-interactable#227]
I see a lot of old PR and Issues. Is this library still maintained?

**/CC:** @rotemmiz @ButtersHub @silyevsk @LoyalBlocks-tzachi

**Comment by rotemmiz** [comment]
We would love to keep it maintained but don't have the capacity for that.
We have a "looking for a maintainer" notice in the readme. https://github.com/wix/react-native-interactable/blob/master/README.md#looking-for-a-maintainer

We'd love to discuss it if you want.

**Comment by geminiyellow** [comment]
oh, i hope it has a web version, but ...

**Comment by mnlbox** [comment]
@rotemmiz thanks for your attention but please merge some critical PR like https://github.com/wix/react-native-interactable/pull/211 before leave this project because this package is a main dependency for https://github.com/wix/react-native-ui-lib and without https://github.com/wix/react-native-interactable/pull/211 now react-native-ui-lib isn't compile and useless in action.
