### ISSUE TITLE
Interactable View not found in the UIManager?

### ISSUE THREAD

**Issue by baiyuli** [wix/react-native-interactable#228]
![simulator screen shot - iphone 6 - 2018-09-04 at 18 56 26](https://user-images.githubusercontent.com/29209803/45066627-1fbd6180-b074-11e8-86e2-91a29a78054d.png)

Anyone have any idea how this could be fixed? I installed and linked the package as instructed, and I've imported Interactable into my project. Not sure why this is showing up.

**Comment by Vishalgwebs** [comment]
I have facing same issue. Any solution ?

**Comment by mtzfactory** [comment]
Me too...

This is my package.json

├── @babel/core@7.1.2
├── @babel/runtime@7.1.2
├── babel-jest@23.6.0
├── jest@23.6.0
├── metro-react-native-babel-preset@0.47.0
├── node-pre-gyp@0.10.3 extraneous
├── react@16.5.0
├── react-native@0.57.1
├── react-native-firebase@5.0.0
├── react-native-interactable@0.1.10
├── react-native-link-preview@1.3.4
├── react-native-modalbox@1.6.0
├── react-native-navigation@2.0.2569
├── react-native-share-extension@1.2.1
├── react-native-shared-group-preferences@1.1.13
├── react-native-ui-lib@3.3.239
├── react-native-vector-icons@5.0.0
└── react-test-renderer@16.5.0

**Comment by anhanh** [comment]
Got this issues on android as well

**Comment by leojle** [comment]
For android: You need to link react-native-interactable 
add in /android/settings.gradle: //Make sure the path is correct in node_modules, it might change due to version
```
include ':react-native-interactable'
project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/lib/android')
```

add in /android/app/build.gradle:
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(path: ':react-native-navigation')
    implementation project(path: ':react-native-interactable')
}
```
In MainApplication.java import and instantiate Iteractable.

```
import com.wix.interactable.Interactable;
...
protected List<ReactPackage> getPackages() {
        // Add additional packages you require here
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
            new Interactable()
            // eg. new VectorIconsPackage()
        );
    }
```

**Comment by phonganhhung9xtb** [comment]
same me on iOS. any solution?

**Comment by leojle** [comment]
@phonganhhung9xtb what I did for IOs was to link (react-native link react-native-interactable) the lib and then did this

Manually link via Cocoa Pods (iOS)

Add the following to your Podfile and run **pod update**:
pod 'Interactable', :path => '../node_modules/react-native-interactable'

**Comment by phonganhhung9xtb** [comment]
> @phonganhhung9xtb what I did for IOs was to link (react-native link react-native-interactable) the lib and then did this
> 
> Manually link via Cocoa Pods (iOS)
> 
> Add the following to your Podfile and run **pod update**:
> pod 'Interactable', :path => '../node_modules/react-native-interactable'

yes! i just resolve it as your way :)) thank anyway!

**Comment by parthv21** [comment]
How to fix this in expo?

**Comment by valhallaferrer** [comment]
Got this issues on android as well. @leojle, your android solution doesnt fix it.

**Comment by tassoruas** [comment]
I'm getting the same error too.. This all didn't fixed Android problem.

**Comment by terryttsai** [comment]
Getting this issue as well

**Comment by AlexandreLage** [comment]
> How to fix this in expo?

You will need to eject from Expo.
Expo does not allow 'linking'.

I hope it helps who are using Expo.

**Comment by marikani** [comment]
> How to fix this in expo?

You have any solution for this error in Expo.I am new to expo.

**Comment by DanleyCr7** [comment]
in the version I'm using 0.62.2 it's working, follow the manual link as below:
version "react-native-interactable": "^2.0.1"

1. android/app/build.gradle > dependencies
implementation "com.facebook.react:react-native:+" // From node_modules
// https://github.com/wix/react-native-interactable
implementation project(path: ":react-native-interactable") <-- Add this line

2. android/settings.gradle
rootProject.name = 'yourappname'
apply from: file("../node_modules/@react-native-community/cli-platform-> android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':react-native-interactable' <-- Add this line
project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/lib/android') <-- Add this line

include ':app'

3.android/app/src/main/java/.../MainApplication.java
import com.wix.interactable.Interactable; <-- Add this line

// Packages that cannot be autolinked yet can be added manually here, for example:
// packages.add(new MyReactNativePackage());
packages.add(new Interactable()); <-- Add this line

I hope for you too

**Comment by Kouznetsov** [comment]
As @DanleyCr7 specified, you have to manually link the library. Follow his instructions.
