### ISSUE TITLE
Build Failed on RN 0.56

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-interactable#231]
Hello, I am writing this due to a error that keeps coming up.

"no suitable constructor found for Event(int) constructor Event.Event() is not applicable (actual and formal argument lists differ in length) constructor Event.Event(int,long) is not applicable (actual and formal argument lists differ in length)"

I don't know how this is being produced and I am wondering who else is having this problem?

**Comment by Inbal-Tish** [comment]
Soon we'll publish our upgrade from RN54 to RN 57.
In the meantime, I am closing the issue as a part of an effort to clean up and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.

**Comment by UnnikrishnanBhargavakurup** [comment]
I'm still facing this issue, how i can fix this?
