### ISSUE TITLE
crash app android when i drag Interactable.View

### ISSUE THREAD

**Issue by chienvu123** [wix/react-native-interactable#234]
<Interactable.View
          style={{
            width: '100%',
            position: 'absolute',
            bottom: 0,
          }}
          animatedValueY={this.deltaY}
        >
          <View
            style={{
              height: 40,
              width: '100%',
              alignItems: 'center',
              justifyContent: 'center',
              borderBottomColor: '#eceff1',
              borderBottomWidth: 1,
              backgroundColor: '#FFF',
            }}
          >
            <View
              style={{ backgroundColor: '#004d40', width: 50, height: 4 }}
            />
          </View>
        </Interactable.View>
version: 
-  "react": "16.3.1",
-  "react-native": "0.55.4",
-  "react-native-interactable": "^0.1.10"

please!

**Comment by midoalone** [comment]
You have to add snapPoints property
example:
`<Interactable.View
					snapPoints={[{ y: 0 }, { y: -180 }]}
					verticalOnly={true}
					>
					<View />
				</Interactable.View>`
