### ISSUE TITLE
Animate rotation

### ISSUE THREAD

**Issue by sebastijandumancic** [wix/react-native-interactable#239]
Hi all. Is it possible anyhow to animate the View's rotation based on horizontal swiping? Something like interpolate from Animated, but using interactable. Thanks!

**Comment by woodpav** [comment]
Yes use the `animatedValueX` prop and interpolate it to create the rotation transform.

**Comment by sebastijandumancic** [comment]
Any examples for this? Is this any way different than using direct interpolation on Animated.Value (with or without interactable, regarding performance? I'm using Animated library with PanResponder and have some performance issues using onPanResponderMove and interpolation, and I'm wondering if this can help in any way? Thanks.

**Comment by woodpav** [comment]
Animated interpolation uses the driver of whatever value(s) you are interpreting. Using interpolate on the animatedValueX prop will not decrease performance because it useNativeDriver: true. You are getting lag for PanResponder because PanResponder is implemented in JS.

**Comment by woodpav** [comment]
Make sure you set the nativeDriver prop for Interactable.View

**Comment by sebastijandumancic** [comment]
Thanks for the help, we can close this issue. For the internet wanderer that arrived here, lagging problem on Android was because I had borderRadius: 1000, and that killed all the FPS in the app.
