### ISSUE TITLE
'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by emretekince** [wix/react-native-interactable#25]
/node_modules/react-native-interactable/ios/Interactable/InteractableViewManager.h:10:9: **'React/RCTViewManager.h' file not found**

`#import <React/RCTViewManager.h>`

Using react-native 0.35.0

**Comment by marcmo** [comment]
I have the same thing with RN 0.50.4 and interactable 0.1.10

**Comment by Komalov** [comment]
RN53, the same

**Comment by alexandria-g** [comment]
The header declarations in Interactable are searching in this directory:

[project root]/ios/Pods/Headers/Public/React/ or [project root]/ios/Pods/Headers/Public/React/React/

What you need to do is search in /Base or /Views subfolders at this path for the correct header file, then add that into the header file path declaration in the Interactable files.

eg
#import <React/RCTViewManager.h> becomes #import <React/Views/RCTViewManager.h>

**Comment by abe732** [comment]
Thanks for the tip @alexandria-g !

When I tried that it threw another issue down the road saying that 'RCTDirectEventBlock' is an unknown name type. Any suggestions / help in resolving that? Would really appreciate any tips!
