### ISSUE TITLE
onSnapStart not being called

### ISSUE THREAD

**Issue by sachinB94** [wix/react-native-interactable#259]
`onSnapStart` is not being called with the latest build.

react-native@0.42.0
react-native-interactable@1.0.0-alpha.1

Usage:

```js
<Interactable.View
  verticalOnly
  snapPoints={snapPoints}
  boundaries={{ top: -300 }}
  initialPosition={snapPoints[snapPoints.length - 1]}
  animatedValueY={this._deltaY}
  onSnapStart={this.onSnapStart}
  onSnap={this.onSnap}
>
  {/*  */}
</Interactable.View>
```

```js
onSnapStart = event => {
  console.log('onSnapStart', event);
};
```

I can see `onSnapStart` in the `typings/react-native-interactable.d.ts` file, but, it is not being called.

**Comment by sachinB94** [comment]
Closing it.

Had to relink the react-native-interactable package. Works now.

**Comment by zcmgyu** [comment]
Still wasn't fixed on1.0.0-alpha.1
