### ISSUE TITLE
MapPanel buggy interpolation. HELP!

### ISSUE THREAD

**Issue by alisherakb** [wix/react-native-interactable#269]
In **MapPanel** interpolation inside Animated.View starts in reverse order on restart until you start to drag:

![image 2019-02-28 21 30 05](https://user-images.githubusercontent.com/26904008/53592939-0408c300-3ba0-11e9-8a38-8fafe8be87fc.jpg)

---

Reproducing:
It may not appear instantly on this example. But if you try 10 restarts, 2-3  of them will be buggy(reverse interpolation) until you start to drag. 
Making more complex animations(backgroundColor, Height, SVG paths) may decrease successful restart to 0, meaning that all your interpolations will be reversed.

---

Using: 
> animatedNativeDriver={true}

Solves the issue. But limits me on making more complex animations (backgroundColor, Height, SVG paths).

--- 
"react-native": "0.57.3"
"react-native-interactable": "^0.1.10"

---
Need your help guys, please!!!

**Comment by huuthinh245** [comment]
i' have issue when debug . I guess the deltaY reset to 0. Any solution pls

**Comment by huuthinh245** [comment]
did you solve it>?

**Comment by alisherakb** [comment]
> did you solve it>?

Nope. Still looking for a solution...

**Comment by rjruizes** [comment]
https://github.com/wix/react-native-interactable/issues/121 looks like the same issue, and it's from 2017

**Comment by rjruizes** [comment]
The problem is that sometimes animatedEvents are fired on init with y=0, instead of y=initialPosition.
Here's a hacky workaround:
Edit [this file](https://github.com/wix/react-native-interactable/blob/a1477549909ecd8f4dc4a0f7e9b898587f48d7c1/lib/src/InteractableView.js), modifying lines 31-39 to the below:

```
      this._animatedEvent = (event, gestureState) => Animated.event(
        [{
          nativeEvent: {
            x: this.props.animatedValueX,
            y: event.nativeEvent.y > 0 ? this.props.animatedValueY : null
          }
        }],
        { useNativeDriver: !!this.props.animatedNativeDriver }
      )(event, gestureState);
```

which checks the value of the incoming event and will only change `animatedValueY` if the event is not zero. For my case, I don't care about y=0.

**Comment by rjruizes** [comment]
I logged the coordinates sent by the native code ([on this line](https://github.com/wix/react-native-interactable/blob/master/lib/ios/Interactable/InteractableView.m#L240)) and I logged the nativeEvent coordinates received by the react-native code (my previous comment).

In successful cases, two events are sent and received, the first sets the InteractableView's center to 0,0, and the second sets the center to the requested initialPosition. 

The bug occurs when two events are sent, but only one is received on the react-native side. That would be a bug with the react-native bridge.

**Comment by alisherakb** [comment]
> this._animatedEvent = (event, gestureState) => Animated.event(
>         [{
>           nativeEvent: {
>             x: this.props.animatedValueX,
>             y: event.nativeEvent.y > 0 ? this.props.animatedValueY : null
>           }
>         }],
>         { useNativeDriver: !!this.props.animatedNativeDriver }
>       )(event, gestureState);

You saved my smooth project. Thank you a lot!
