### ISSUE TITLE
how to change the swipe back to original state after I press the delete button

### ISSUE THREAD

**Issue by colin3dmax** [wix/react-native-interactable#29]
[![alt text](https://media.giphy.com/media/3oKIPlrC9LRunLkxt6/giphy.gif "issues demo")](https://media.giphy.com/media/3oKIPlrC9LRunLkxt6/giphy.gif)

I use react-native-interactable to make a swipeout demo 
After I press the delete button，the UI rerender but the swipe effect is still there.

**Comment by colin3dmax** [comment]
![Uploading 3月-21-2017 06-19-36.gif…]()

**Comment by colin3dmax** [comment]
I need the right effect is  when I press delete button,this row delete.
The next row is close state.

**Comment by iamtommcc** [comment]
Would the new `setVelocity` function described in #18 be of assistance? (iOS only for now)

**Comment by colin3dmax** [comment]
I found the setVelocity funciton ,But don't known how to use the function.
<Interactable.View ref={comp=>this.refComp= comp} ... >...</Interactable.View>
The Doc not write how to use the setVelocity function
this.refComp.setVelocity(...)  ? 

I tried,but got undefine setVelocity  error

**Comment by colin3dmax** [comment]
@iamtommcc 

I found the setVelocity funciton ,But don't known how to use the function.
<Interactable.View ref={comp=>this.refComp= comp} ... >...</Interactable.View>
The Doc not write how to use the setVelocity function
this.refComp.setVelocity(...) ?

I tried,but got undefine setVelocity error

**Comment by tasarsu** [comment]
Hello Colin can you please try `key` attribute with a unique id for the render method of listview?

```javascript
renderRow (line, sectionID) {
    return (
      <Row key={line.id} ...
```

**Comment by talkol** [comment]
Seconding the answer by @tasarsu. What happens here is that React is recycling the component and "moving" your rows into the existing native components instead of destroying and creating new ones. This can be avoided by letting React know that these components are different instances, ie using the `key` prop for the rows. React will not recycle the native view if the key is different.

**Comment by colin3dmax** [comment]
I will try @tasarsu's way.
Thanks @tasarsu and @talkol .

**Comment by talkol** [comment]
Please close the issue if you manage to get this working. If not, please post a small demo project and we'll help you fix it

**Comment by talkol** [comment]
Please reopen if this issue is still a problem

**Comment by yash2code** [comment]
@colin3dmax  can you provide us with the code

**Comment by zhaiyjgithub** [comment]
I try it but it doesn't work.
