### ISSUE TITLE
onDrag and onSnap props are not passing the event object

### ISSUE THREAD

**Issue by cspicuzza** [wix/react-native-interactable#308]
Attached is a screenshot from my console.  This is a log from the onSnap event param being passed into my method

I expected to see:
```
{ index, id }
```
instead have:

![Screen Shot 2020-04-10 at 11 41 42 AM](https://user-images.githubusercontent.com/4442172/79014694-4846f080-7b20-11ea-8109-db35eb275928.png)

**Comment by josecanizares** [comment]
You can see these properties inside the nativeEvent
