### ISSUE TITLE
Expo friendly? 

### ISSUE THREAD

**Issue by JamieGarcia123** [wix/react-native-interactable#325]
HI just curious if this package is Expo friendly? getting this error : Invariant Violation: requireNativeComponent: "InteractableView" was not found in the UIManager.

but from what I understand is Expo auto links unless its not compatible. Think this is the case?

**Comment by JamieGarcia123** [comment]
nvm i found my answer digging through more

**Comment by imyanglu** [comment]
> nvm i found my answer digging through more
help me,how to relolve？
