### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by Ehesp** [wix/react-native-interactable#34]
After linking, and also [updating the settings.gradle](https://github.com/wix/react-native-interactable/issues/12#issuecomment-286670527), I'm faced with a build issue on Android:

> android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

This appears multiple times for other sources such as `'android:TextAppearance.Material.Widget.Button.Borderless.Colored'`.

RN 0.42
Mac OS Sierra 10.11.16

**Comment by rotemmiz** [comment]
It's hard to understand​ what's the issue without taking a look at your build.gralde files.
I don't think this has to do with interactable since we don't use this theme in the library.

Please post your build.gradle if possible.

**Comment by Ehesp** [comment]
Fixed it, there's was an issue with the SDK version in my build.gradle. Sorry!

**Comment by rotemmiz** [comment]
Just for a future reference, the error was that react-native-interactable included the support lib itself. Fixing it in your project was only possible if you chose to use build tools 25.1.0.

It's not a limitation anymore (14592441bf84c89edff40ee93dcc42082aba7acc)

**Comment by Ehesp** [comment]
I did upgrade the build tools to that, thanks for sorting!
