### ISSUE TITLE
Touches not detected below notifications pulldown.

### ISSUE THREAD

**Issue by jirkaakres** [wix/react-native-interactable#36]
I have the exact same setup as in the NotifPanel Real Life Example. The problem **on iOS** is no touches are detected in the screen below the panel (try wrapping the image into TouchableOpacity, it will not do a thing). On Android it works fine.

**Comment by jirkaakres** [comment]
Never mind, I have figured it out.
For anyone encountering the same issue - the example is set up a bit clumsily. The notifications View there is se up as `absolute`ly positioned, at `top: 0` and `left:0`. That means that it - on iOS at least - obscures the View underneath it from touches, even if it is moved elsewhere by being `Interactable.View`. So for this to work, I needed to move the notifications panel out of the screen to begin with and then set the snap points and boundaries relative to this new position, which means snap points are at y: 0 and y:Screen.height and boundaries are the same.

**Comment by talkol** [comment]
haha, I whipped those examples a couple of days before the conf so they were brute forced :) Feel free to PR a better implementation so people could reuse them

**Comment by talkol** [comment]
There's actually a simpler way I believe to fix your issue without changing the layout of entire example. 

The Interactable.View is inside a container that is absolutely positioned, right? And this container is what obscuring the touches, right? All you have to do is add the `pointerEvents` prop to it. See its docs here: https://facebook.github.io/react-native/docs/view.html#pointerevents

`pointerEvents='box-none'` defines that the container is never the target of touch events but it's subviews can be which is exactly what you want.

**Comment by jirkaakres** [comment]
Oooh interesting, I haven't noticed that. I think the rearrangement of the layout can be a bit cleaner maybe? Because you don't have to deal with negative offsets... I don't know, I guess it boils down to personal preference :-) Anyway I'll keep that prop in mind for other touch-related problems, thanks.
