### ISSUE TITLE
Issue with animated native driver

### ISSUE THREAD

**Issue by matpaul** [wix/react-native-interactable#39]
Hey! Thanks for real cool work! So

There is an issue if i set animatedNativeDriver={true} and then my component with interactable re-render - is's fail with this error 
<img width="371" alt="screen shot 2017-03-26 at 15 55 34" src="https://cloud.githubusercontent.com/assets/1817112/24331445/5fc46fde-123d-11e7-82f3-cf587d9a3b24.png">

To reproduce take any example and add state value, then change it

**Comment by talkol** [comment]
yes, the native event support in Animated is still experimental.

I'm still waiting for Animated to sort the native driver issues.
I have a feeling this problem is not related to us.

Also, check if this screen is appearing in release. It might be a debug issue only.

**Comment by matpaul** [comment]
I found same issue (description the same JSON circular etc..) but it was used with Scroll/List and guys said that it fixed 
https://github.com/facebook/react-native/issues/11760

I builded it in release mode - nope still issue 
<img width="716" alt="screen shot 2017-03-26 at 21 29 24" src="https://cloud.githubusercontent.com/assets/1817112/24334015/5b42dad0-126b-11e7-94f9-8bdc56d567ff.png">

**Comment by talkol** [comment]
Do you maybe know what is the commit that fixed the issue?

If I remember correctly, we copied the code from a recent implementation of Animated.ScrollView

**Comment by matpaul** [comment]
No, but I found some interesting code about animated  scroll view

https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/Animated.js

**Comment by matpaul** [comment]
Ohh i re-check implementation js part native-interactable and same thing, but i sure that trouble on native-interactable side

**Comment by motiazu** [comment]
+1

I can confirm, happened to me whenever I used the native driver and clicked in an Interactable.
By the way the native driver is working perfectly for me when I use properties it supports.

**Comment by talkol** [comment]
maybe you can compare the native implementation to what's working in scroll view and find the difference?

This is the place in native where the animated event is reported:
https://github.com/wix/react-native-interactable/blob/master/ios/Interactable/InteractableView.m#L232

**Comment by matpaul** [comment]
I did some compare and found that AnimatedImplementation do some additional work for scroll 
https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/AnimatedImplementation.js#L1761

**Comment by talkol** [comment]
@silyevsk can you please help @matpaul investigate this?

**Comment by silyevsk** [comment]
@talkol @matpaul -
There's this code in `AnimatedImplementation.js`:
```javascript
    _detachNativeEvents(props) {
      // Make sure to get the scrollable node for components that implement
      // `ScrollResponder.Mixin`.
      const ref = this._component.getScrollableNode ?
        this._component.getScrollableNode() :
        this._component;

      for (const key in props) {
        const prop = props[key];
        if (prop instanceof AnimatedEvent && prop.__isNative) {
          prop.__detach(ref, key);
        }
      }
    }
```

So if getScrollableNode is defined, then a number is sent over the bridge instead of the view and there's no crash. Fixed this in https://github.com/wix/react-native-interactable/tree/39_native_driver_issues_on_ios
