### ISSUE TITLE
Manual Linking in iOS using react-native as a Pod

### ISSUE THREAD

**Issue by guilharj** [wix/react-native-interactable#40]
Hi Guys , I here to share with you a situation using interactable lib in a already existing brownfield app. 

The installation instructions sais that we need do make this 2 steps ( http://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) 

But if you are using react-native as a pod , including te lib in a PodFile, you will face a problem building your app.  The Interactable lib does not find the React lib . 

We solved this issue creating another pod target named Interactable , and pointing to the node_modules right directory. At this target we declared React lib dependencies.  After that run a $ pod update solved this issue. 

What you think about including this steps ?  Maybe someone is working in create a podSpec to interactable already. 

Hope that this sharing helps others !

**Comment by talkol** [comment]
Can you do a PR on the README with these instructions?
I think the best would be to add a link to a new file called INSTALL-PODS.md that will contain the instuctions and link to it from the main README

Also, if you're interesting in creating a podSpec it will be nice. We don't use Pods in our projects :/

**Comment by guilharj** [comment]
Sure, weekend job !

**Comment by talkol** [comment]
We're still looking forward to your addition :)

**Comment by guilharj** [comment]
@talkol  Can you give me permission to push a branch . This is my first time in this project. 

Thanks

**Comment by guilharj** [comment]
@talkol  forget it . I've realised that someone already did it. We should check the PR and close this issue

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
