### ISSUE TITLE
setVelocity not working

### ISSUE THREAD

**Issue by jp928** [wix/react-native-interactable#41]
I am not sure this is a bug or I used the api in a wrong way.

```html
<Interactable.View
  style={Styles.modal} 
  ref={ref => (this.modal = ref)}
  initialPosition={{ y: -screenHeight }}
  snapPoints={[{ y: -screenHeight }, { y: 0 }, { y: screenHeight }]}
  boundaries={{ top: -screenHeight, bottom: 0 }}
  verticalOnly>
</Interactable.View>
```

when I use `this.modal.setVelocity({ y: 2000 });` it works fine. 
However, `this.modal.setVelocity({ y: -2000 });` doesn't dismiss the modal view.

**Comment by talkol** [comment]
Are you running on Android?
There's an open bug on Android that's fixed I think in this branch:
https://github.com/wix/react-native-interactable/tree/androidFixes

what happens there is that if you place the dismiss event on a button that's found on the modal itself, then the touch event of the tap registers as if you are dragging the modal and setVelocity doesn't work if you're in the middle of dragging

can you try and work with the branch to see if this resolves the issue?

it will be merged into master tomorrow

**Comment by talkol** [comment]
btw, I added to master `snapTo` imperative command for iOS.. you can try it out as well

**Comment by talkol** [comment]
@jp928 can you confirm the issue was resolved with latest version?

**Comment by rotemmiz** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.

Thanks for your contribution.
