### ISSUE TITLE
[Feature Request] snap disable

### ISSUE THREAD

**Issue by jp928** [wix/react-native-interactable#42]
is that possible to disable the snap on the element <Interactable.view /> cause I want to use setVelocity to control the animation only.

**Comment by talkol** [comment]
you want to disable dragging by the user?

or do you not want to snap to the pre-defined position at all?

**Comment by jp928** [comment]
I want to disable the user dragging.

I am case, when I build a modal view with interactable libraray, sometimes I want to use button to popup the modal. however, in some situation, I don't want to dismiss the modal by dragging the modal.

**Comment by talkol** [comment]
It's a cool feature, let's add it. 

In the meantime, you can do the following:

When you don't want the modal to be dismissed, `setState()` and change the `snapPoints` prop of the Interactable view and only leave one point (remove the point outside the screen). When the user can dismiss, run `setState()` again and add the missing `snapPoint`

**Comment by talkol** [comment]
Added support on master for iOS only, take a look if this is what you want. @ButtersHub Android next?
