### ISSUE TITLE
How to catch onDrag ?

### ISSUE THREAD

**Issue by Deevent** [wix/react-native-interactable#43]
Hello,

I'm wondering how I can possibly catch an onDrag event on my Interactable.View because I want my UI to change when the user is dragging.
I didn't saw any prop that could do this in the doc.

**Comment by portons** [comment]
@Deevent Did you try using [animatedValueY](https://github.com/wix/react-native-interactable/blob/master/PROPS.md#animatedvaluey-animatedvalue) and [animatedValueX](https://github.com/wix/react-native-interactable/blob/master/PROPS.md#animatedvaluex-animatedvalue)? They'll both changed whenever you drag your Interactable. And then, using the Animated module, you can hook up other components and change accordingly. See ['Animating other views according to Interactable.View position'](https://github.com/wix/react-native-interactable#usage)

**Comment by Deevent** [comment]
Thank you it worked !
