### ISSUE TITLE
How can I move to snapPoint programmatically ?

### ISSUE THREAD

**Issue by Deevent** [wix/react-native-interactable#44]
Hello,

I need to be able to move an Intractable.View to a snapPoint by providing the index. I've tried with setVelocity, but the problem is that the view is moved relatively to it's current position. I have a lot of items on my screen that need to be swapped when you drag one on another.

How can I achieve that ?

**Comment by talkol** [comment]
I'm not really sure I understand the use-case, can you explain it with more detail please?

**Comment by Deevent** [comment]
Very simple example of my use case :

I have 3 Intractable.View and each of them have 3 snapPoints corresponding to the other views placement.

Something like that :
1.
`snapPoints={[
    {x: 0},
    {x: 100},
    {x: 200}
]}`

2.
`snapPoints={[
    {x: -100},
    {x: 0},
    {x: 100}
]}`

3.
`snapPoints={[
    {x: -200},
    {x: -100},
    {x: 0}
]}`

I also have an array telling me which view is at which index : [1, 2, 3]

Now I want to drag my first view on to for example the third snapPoint (x: 200) and my third view should automatically snap to it's first snapPoint (x: -200) because the sender had index 1 in my array.
Now my array looks like that : [3, 2, 1].

I could achieve that with setVelocity but I would have to do a lot of if statements based on the sender id and it's current index. But I want to know if there's an easier way for example telling to a view : "Now snap yourself to the snapPoint at index 1"

**Comment by talkol** [comment]
I added to master an imperative command called `snapTo` which does what you want. iOS only for now. @ButtersHub can you add Android support?

**Comment by ButtersHub** [comment]
sure, ill do it.

**Comment by Deevent** [comment]
@talkol Thank you very much ! Saves me a lot of time ! Very great work here :)

**Comment by ButtersHub** [comment]
Android implemented as well.

**Comment by sondremare** [comment]
I love the short response time here guys! Keep up the good work <3

**Comment by talkol** [comment]
Please reopen if anything still needs to be improved

**Comment by leshaivanovsky** [comment]
guys! a silly question, sorry how can we do a snapTo with animation?

**Comment by Deevent** [comment]
@leshaivanovsky I think that it's animated by default...
