### ISSUE TITLE
Toggle Interactable? 

### ISSUE THREAD

**Issue by GeorgeA93** [wix/react-native-interactable#45]
Is there any way to toggle the "Interactability" of a view? Basically what I am trying to do is only allow a user to interact with my view after they have performed another action such as pressing another button.

I have a [scrollable tab view](https://github.com/skv-headless/react-native-scrollable-tab-view) where one tab contains a list of images, where each image takes up the full width of the screen. Imagine this: (with limited white space)

![687474703a2f2f692e696d6775722e636f6d2f4572413247516f2e676966](https://cloud.githubusercontent.com/assets/6816735/24530363/5df77c5e-15a9-11e7-9ae5-7781f47f859c.gif)

But you can swipe left and right to change tabs.

I am trying to achieve "swipeable" cards and swipe to change tabs. Thus, in order to swipe a card you have to perform another action to enable the interaction, such as pressing a button or a long press. Otherwise you will only ever be able to swipe the cards and not change tab.

**Comment by portons** [comment]
@GeorgeA93, You could always make a wrapper component, give it a prop 'disabled', and, depending on the prop, render either:

`<View> { this.props.children } </View>`

OR

`<Interactable.View> { this.props.children } </Interactable.View>`

**Comment by GeorgeA93** [comment]
@portons Thank you for the suggestion, I am currently doing something similar to that atm but your solution is cleaner. 

I was wondering wether there was a more built in way to do it really.

**Comment by talkol** [comment]
There was also issue #42 that requested something similar. And issue #15 which could be related.

I thought about combining them all to the same solution. Want to help design the API? What should the prop be?

Also, there's another possible temporary solution. You can wrap your Interactable with a View and on this view play with its [`pointerEvents`](https://facebook.github.io/react-native/docs/view.html#pointerevents) prop. This will control whether the Interactable receives touch events or not.

**Comment by talkol** [comment]
There is now a built in way on master with `dragEnabled`, iOS only currently, Android coming soon

**Comment by GeorgeA93** [comment]
@talkol `dragEnabled` is what I need! Thank you for that.

**Comment by talkol** [comment]
I'm reopening until Android support is in master

**Comment by ButtersHub** [comment]
@talkol , Android now supports _dragEnabled_

**Comment by FakeYou** [comment]
I don't know if this is the right place but `dragEnabled` has slightly different behaviour on Android and iOS. 

I have a use-case where I set `dragEnabled` based on a `alertArea`. When the view enters the `alertArea` (using the `snapTo` method) I set `dragEnabled` to `true`, when it leaves I set it to `false`. On iOS this change of `dragEnabled` will stop any dragging and snap to the nearest point. On Android the user can keep dragging until the user lets go. Only from then on is dragging disabled.

I'm not sure which behaviour is more desirable but I would be nice if it was consistent.

**Comment by talkol** [comment]
@FakeYou lol, can you choose between the two, I have a hard time imagining what makes more sense :)

**Comment by FakeYou** [comment]
@talkol well for my particular use-case the iOS version makes more sense.

**Comment by ButtersHub** [comment]
@FakeYou, thanks for the PR, it was merged to master.
I added test under the "Alert Areas and Drag Event".

**Comment by talkol** [comment]
Seems resolved to me, please reopen if anything isn't working as expected
