### ISSUE TITLE
onResponderRelease

### ISSUE THREAD

**Issue by neverlan** [wix/react-native-interactable#47]
Hi guys :)

Is there a way to get an event just after the user stopped dragging ? Something like onResponderRelease with panResponder.

I need to trigger an action only when the user stopped dragging and moved at least to a specific threshold.

**Comment by talkol** [comment]
No, I want to add that though. It's an important feature

We only have events on:
1. view snapped to a point
2. view stopped
3. view entered some specific area

**Comment by talkol** [comment]
I added support for `onDrag` event on master. Currently iOS only. @ButtersHub can you add Android?

**Comment by neverlan** [comment]
Great works :)

**Comment by ButtersHub** [comment]
Android done as well.

**Comment by talkol** [comment]
Please re-open if this is not working as expected
