### ISSUE TITLE
App crashes when hot reloading enabled

### ISSUE THREAD

**Issue by ghsamm** [wix/react-native-interactable#49]
Hey guys,

I'm on Android 5.1. When hot reloading is enabled, touching the `Interactable.View` element crashes the app.

**Comment by ButtersHub** [comment]
Please try reproduce the issue with the latest master version.
If still reproduced, specify the Components you use inside the Interactable.View.

**Comment by talkol** [comment]
@ghasmm, was the issue resolved by the fix in master? I want to close the issue

**Comment by ghsamm** [comment]
So, here's what happened, I tried to reproduce the issue with my own custom element but this time the app crashed even when hot reloading is disabled. After many failed attempts, I copied the code from the RowAction1 example. It worked fine even with hot reloading. Maybe there's some CSS that has to be applied to the interactable element ? or maybe it's because of `styled-components` ?
Here's what my code that crashed looked like:
```javascript
import React, { Component } from 'react'
import { Text, AppRegistry } from 'react-native'
import Interactable from 'react-native-interactable'
import styled from 'styled-components/native'

const AppContainer = styled.View`
  flex: 1;
  background-color: white;
`

export default class MyApp extends Component {
  render() {
    return (
      <AppContainer>
        <Interactable.View
          style={{
            backgroundColor: 'grey'
          }}
          horizontalOnly={true}
          snapPoints={[{x: 0}, {x: 200}]}>
            <Text>Some random text</Text>
            <Text>Some random text</Text>
            <Text>Some random text</Text>
        </Interactable.View>
      </AppContainer>
    )
  }
}

AppRegistry.registerComponent(
  'MyApp ',
  () => MyApp 
)

```

**Comment by ghsamm** [comment]
@talkol good news. I updated to 0.0.8 and now everything seems to work fine. I guess you can close the issue now 😄

**Comment by ButtersHub** [comment]
@ghsamm , Thx.
