### ISSUE TITLE
ScrollView not respond when in Interactable.View [android]

### ISSUE THREAD

**Issue by Cholern** [wix/react-native-interactable#50]
When i use scrollView in Interactable.View on ios it works fine, but on android it not respond.

**Comment by portons** [comment]
See https://github.com/wix/react-native-interactable/issues/35#issuecomment-290460550

**Comment by talkol** [comment]
It should work on Android if the ScrollView scrolls in one direction and the Interactable moves in the perpendicular direction

If they both move in the same direction, it's much more difficult, see @portons thread

**Comment by talkol** [comment]
Please re-open if this is a different issue than #35
