### ISSUE TITLE
Add direction specific touch blocker for Android

### ISSUE THREAD

**Issue by portons** [wix/react-native-interactable#51]
Is there a possibility to add, in addition to 'blockAllTouch', something like 'blockVerticalSwipe' && 'blockHorizontalSwipe'? Having some problems with a ListView that sits inside a horizontal carousel, that sits inside a vertical Interactable. The blocker _does_ solve the problem of the ListView and it's scrolling regularly, but I can't swipe inside the carousel, as all touch events are blocked inside the ListView. If I could block only vertical swipes, the combination of the Interactable + carousel + ListView would've worked.

Sorry I don't just open a PR to solve this - I'm not familiar with neither Objective-C nor Java.

**Comment by portons** [comment]
@LoyalBlocks-tzachi:
Tried to add it by myself, please see whether you'd want to add this feature:
https://github.com/wix/react-native-interactable/pull/52

**Comment by uriklar** [comment]
+1

**Comment by talkol** [comment]
We definitely want the feature, @ButtersHub will review it soon. He just wanted to finish with the new iOS features I added (snapTo, dragEnabled, onDrag event)

**Comment by talkol** [comment]
@portons sorry for the lack of progress, everybody has been on vacation for the last week (due to Easter and Passover holidays). Things should get back to normal around Tue

**Comment by ButtersHub** [comment]
merged @portons's PR to touchBlockerBranch, you are welcome to try it, there is new case in the example project, it look like this: 
![interceptionblocker](https://cloud.githubusercontent.com/assets/6397777/25070916/fc428f3c-22b2-11e7-9020-b8335cb57e14.gif)

**Comment by portons** [comment]
@ButtersHub @talkol Thanks a lot! Will test in our project after Passover :)

**Comment by rotemmiz** [comment]
Seems like this is already solved
