### ISSUE TITLE
snapTo not a function (0.0.8)

### ISSUE THREAD

**Issue by suprb** [wix/react-native-interactable#57]
Hi, first of all — thank you so much for all the hard work you guys are doing here. 

I've updated to the latest version (0.0.8) and trying to use the snapTo function without success. I'm getting 'snapTo is not a function'. I'm successfully calling the setVelocity on the same ref, so I know the ref is functional.

Any idea?

**Comment by ButtersHub** [comment]
Hi @suprb, snapTo not working in your case both on Android & iOS ?

**Comment by suprb** [comment]
Hi, only tested on iOS. 

this.refs.menuInstance.setVelocity(y:200) <-- this works.   
this.refs.menuInstance.snapTo({index: 0}) <-- this returns "snapTo not a function"

**Comment by ButtersHub** [comment]
If you navigate to node_modules/react-native-interactable/InteractableView.js did you see the snapTo(params) method in the file ?

**Comment by suprb** [comment]
I got it to work—I updated RN and suddenly it worked.
