### ISSUE TITLE
Gestures that aren't "horizontal" enough are blocked by horizontalOnly

### ISSUE THREAD

**Issue by wsun** [wix/react-native-interactable#63]
While I was playing with some of the examples, I noticed that certain gestures were not resulting in any movement. For example, a SwipeableCard, which has `horizontalOnly` specified would not pick up on certain gestures I was making (e.g. an arc that starts fairly vertical and eventually moves horizontally).

In the [iOS code](https://github.com/wix/react-native-interactable/blob/master/ios/Interactable/InteractableView.m#L331), I see that `gestureRecognizerShouldBegin` uses the heuristic of "more horizontal than vertical" to determine whether it should respond to a gesture. I'm curious whether this was done for performance reasons, or something else? It may be worth adding an additional property that controls this behavior, while leaving `verticalOnly` and `horizontalOnly` to control movement axes.

**Comment by ButtersHub** [comment]
thanks for the comment, we will check this whether this is a bug or not

**Comment by ButtersHub** [comment]
@wsun have you tested this on Android ?

**Comment by wsun** [comment]
I haven't tested on Android -- only iOS. Not sure this is a bug, since it behaves exactly as you would expect after having read the code, but seems more like a design decision to bundle together 1/ movement axis and 2/ gestures to respond to into a single boolean. I can think of situations where one would prefer these unbundled (e.g. if you were making a carousel, you might only want items to move horizontally, but would be fine responding to gestures that start off vertical).

**Comment by rotemmiz** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.

Thanks for your contribution.
