### ISSUE TITLE
Programmatically changing the position

### ISSUE THREAD

**Issue by yoavrofe** [wix/react-native-interactable#68]
I tried to do it, but changing initialPosition has no effect. How can this be done? Can the position be animated? This is important for many applications.
Thanks!

**Comment by ButtersHub** [comment]
You can use imperative SnapTo method (take a look on issue #44)

**Comment by kevinNejad** [comment]
@Blackmamba23  having the same problem. seems like methods are not called in componentDidMount
At some cases, they are not even called in componentDidUpdate either.
I'm still investigating the bug, not sure if it's supposed to be like this or it's a bug.

**Comment by Inbal-Tish** [comment]
Thank you @kevinNejad
