### ISSUE TITLE
Utterly Amazing, Perfect Presentation!

### ISSUE THREAD

**Issue by faceyspacey** [wix/react-native-interactable#7]
How long till this is merged into RN? ;)

**Comment by rotemmiz** [comment]
Thanks @faceyspacey :)
Well, who knows ...

**Comment by talkol** [comment]
I think that we didn't nail the declarative API yet. Let's give it a while until people actually use this in production and once they do, we'll have some suggestions on how to improve the API. Once we're happy with the API it will be pretty easy to add it to RN itself. The impact on the binary size is negligible.
