### ISSUE TITLE
Event when the snap animation starts

### ISSUE THREAD

**Issue by maxs15** [wix/react-native-interactable#70]
Hey guys,
Currently the onSnap event is only called when the animation is done, would it be possible to consider adding an event when the animation starts ?
Maybe two functions onSnapStart and onSnapEnd would be appropriate ?

Thanks, and awesome work on the lib 👍

**Comment by gaberudy** [comment]
This would be very helpful. I'm trying to start an animation to hide (height goes to 0) of a view as the user releases touch and the snap animation kicks in.

I can watch for the release touch event, but I don't know if the snap was started or not.

**Comment by davidskaarup** [comment]
I'm also trying to trigger an animation when the snap event starts so it would be really nice if this feature was added.

**Comment by maxs15** [comment]
Did someone found a way to implement that ?
Trying to dig in the native code, need to find a way to make this work..

**Comment by pfeiffer** [comment]
Would also really like this!

**Comment by Inbal-Tish** [comment]
resolved with PR #147
