### ISSUE TITLE
Deployment target on iOS - Crashing on iOS 8

### ISSUE THREAD

**Issue by janaraj** [wix/react-native-interactable#73]
Hello,

thanks for the plugin. The deployment target for iOS is set to 10.2, was this intentional ? It's crashing with 10.2. However if I change the target to 8.1, an initial test for dragrow seems to be working. Could you please advise ?

Regards,
Jana

**Comment by Inbal-Tish** [comment]
https://github.com/facebook/react-native/issues/19346
