### ISSUE TITLE
How to use 'onStop'?

### ISSUE THREAD

**Issue by naivehhr** [wix/react-native-interactable#81]
https://github.com/wix/react-native-interactable/blob/master/example/src/MoreChatHeads.js
```
onStopInteraction(event) {
    const x = event.nativeEvent.x;
    const y = event.nativeEvent.y;
    console.log(`stopped at x=${x}, y=${y}`);
  }
```
I can't see any log...How should i use it?
Thanks

**Comment by nickvo1604** [comment]
Yes, It seems not work on Android.

**Comment by cinder92** [comment]
its related to #104

**Comment by rotemmiz** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce it.

Thanks for your contribution.
