### ISSUE TITLE
alertAreas and influenceArea properties

### ISSUE THREAD

**Issue by yshterev** [wix/react-native-interactable#82]
Hello,
I am trying to create a simple drag and drop. I have a draggable button and a drop target component, almost the same as the [AlertArea example](https://github.com/wix/react-native-interactable/blob/master/example/src/AlertAreas.js).

I can't seem to align the `alertAreas` and its `influenceArea` properties with the drop target position.

Can someone explain how this works?

The drop target components in the example are using screen size for calculations. `influenceArea` in the is using single values.

1. I see there is some connection, but how are the screen size values used in the [View](https://github.com/wix/react-native-interactable/blob/9886e6e6fa5a39af08819636c0d11922bae266e7/example/src/AlertAreas.js#L22) exactly related to the [influenceArea ](https://github.com/wix/react-native-interactable/blob/9886e6e6fa5a39af08819636c0d11922bae266e7/example/src/AlertAreas.js#L34)?

2. Why is 75 subtracted [here](https://github.com/wix/react-native-interactable/blob/9886e6e6fa5a39af08819636c0d11922bae266e7/example/src/AlertAreas.js#L7)?

3. Is there anything specific about the layout in general that can affect `influenceArea` positions ?

**Comment by yshterev** [comment]
I think I figured it out.
The screen dimensions are used for consistency. The [subtracted 75](https://github.com/wix/react-native-interactable/blob/9886e6e6fa5a39af08819636c0d11922bae266e7/example/src/AlertAreas.js#L7) compensate for device buttons at the bottom and notification area on top (In my case android).

If you have a header and content section below it you also will have to subtract the header height, so screen height correspond to the draggable area only.

`influenceArea` properties correspond to the center of the draggable component, but also need to be calculated using screen dimensions, so they work the same across different device sizes.

**Example:**
If you have a draggable component with `absolute` position located on `bottom: 15`, dragging it up creates negative Y value. It can be tested using `onDrag` and printing `event.nativeEvent.y`. 

`top` and `bottom` properties of  `influenceArea` basically correspond to the minY and the maxY value between which the alert will be triggered. 

`left` and `right` work the same way for minX and the maxX, counting from the center of the draggable component.

Please correct me if i am wrong.

**Comment by sdeleon28** [comment]
@yshterev, if I'm not mistaken `top`, `bottom`, `left` and `right` work as you've described but they are relative to the center **of the screen**, not the component being dragged.

**Comment by yshterev** [comment]
@sdeleon28 Sorry ... I really don't remember what is going on here :) It was a long time ago and I have not used the library since then.
