### ISSUE TITLE
Example with multiple TinderCards

### ISSUE THREAD

**Issue by rodrigofontes** [wix/react-native-interactable#88]
Can show an example with multiple tinder cards?

**Comment by sohooo** [comment]
Here's a demo with multiple cards, with lots of `console.log`s:
https://github.com/sohooo/TinderCards/blob/master/src/App.js

However, there's one problem: the state gets updated correctly to the next card, `render()` is called, but the new card doesn't appear. Any hints?

**Comment by sohooo** [comment]
I found a way to revert the card to its original position with `snapTo()`. This should be replaced with `changePosition()` as soon as the function is published in a new version of the npm module.
https://github.com/sohooo/TinderCards/blob/master/src/App.js#L48

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
