### ISSUE TITLE
Collapsing Header With Scroll freezes 

### ISSUE THREAD

**Issue by barjas** [wix/react-native-interactable#90]
after implementing the example : CollapsingHeaderWithScroll , i noticed the following issue:

1.  drag the Intractable view up , all works fine, the header scales down
2. scroll the content of the Intractable little bit (NOT TO THE END)
3. then the Intractable drag down is NOT active , the screen just cannot be dragged down, to get it working, i had to scroll the content of the scroll view Intractable to the end, and ONLY after that, i can expand the header

**Comment by Inbal-Tish** [comment]
Update for this example screen will be available soon.

In the mean time, I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.

**Comment by justasmig** [comment]
This issue still persists in latest interractable version
