### ISSUE TITLE
CollapsingHeaderWithScrolldemo doesn't work in 0.45.1

### ISSUE THREAD

**Issue by iremlopsum** [wix/react-native-interactable#95]
Trying out CollapsingHeaderWithScroll demo, but it just doesn't work in Android with RN 0.45.1. All of the elements are rendered correctly, but the header doesn't collapse.

Any ideas?

**Comment by tikkichan4** [comment]
Same problem.

**Comment by iksent** [comment]
Same issue, not working: header do not collapse
react-native: "0.48.4"

**Comment by Inbal-Tish** [comment]
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.
