### ISSUE TITLE
Running Example Error : Unable to resolve module react from .../src/interactableView.js : Module does not exist in the module map

### ISSUE THREAD

**Issue by camellieeee** [wix/react-native-interactable#96]
<img width="311" alt="qq20170619-115151 2x" src="https://user-images.githubusercontent.com/18331008/27268971-bd5fee08-54e5-11e7-8a00-67e4504ed3d8.png">
How to get it ?

**Comment by camellieeee** [comment]
npm install react in root , and got it...

**Comment by chourobin** [comment]
@camellieeee can u close this issue if it's solved?

**Comment by LouisonGitzinger** [comment]
solved thx to @camellieeee

**Comment by SFRohan** [comment]
Hi @camellieeee ,

couldn't resolve this issue. 
npm 0.47

Tried this react-native start --reset-cache but does not work
